/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'createdAt' : bigint,
  'author' : Principal,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface FullPost {
  'id' : PostId,
  'content' : string,
  'meTooCount' : bigint,
  'mood' : Mood,
  'createdAt' : bigint,
  'supportCount' : bigint,
  'author' : Principal,
  'commentCount' : bigint,
}
export type Mood = { 'sad' : null } |
  { 'hopeful' : null } |
  { 'stress' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'love' : null };
export type PostId = bigint;
export type Reaction = { 'meToo' : null } |
  { 'support' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[Mood, string], PostId>,
  'getAllPosts' : ActorMethod<[], Array<FullPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reactToPost' : ActorMethod<[PostId, Reaction], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];