/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'hopeful' : IDL.Null,
  'stress' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'love' : IDL.Null,
});
export const FullPost = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'meTooCount' : IDL.Nat,
  'mood' : Mood,
  'createdAt' : IDL.Nat,
  'supportCount' : IDL.Nat,
  'author' : IDL.Principal,
  'commentCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : IDL.Nat,
  'author' : IDL.Principal,
  'postId' : PostId,
});
export const Reaction = IDL.Variant({
  'meToo' : IDL.Null,
  'support' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([Mood, IDL.Text], [PostId], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(FullPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reactToPost' : IDL.Func([PostId, Reaction], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'hopeful' : IDL.Null,
    'stress' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'love' : IDL.Null,
  });
  const FullPost = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'meTooCount' : IDL.Nat,
    'mood' : Mood,
    'createdAt' : IDL.Nat,
    'supportCount' : IDL.Nat,
    'author' : IDL.Principal,
    'commentCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : IDL.Nat,
    'author' : IDL.Principal,
    'postId' : PostId,
  });
  const Reaction = IDL.Variant({ 'meToo' : IDL.Null, 'support' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([Mood, IDL.Text], [PostId], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(FullPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reactToPost' : IDL.Func([PostId, Reaction], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };